import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";
import { ROOT, parseSkill } from "./verify.mjs";

const references = [
  ["motion-contract.md", "Web Motion Contract"],
  ["tool-routing.md", "Capability Routing"],
  ["design-contract.md", "Design Contract"],
  ["plan-execute.md", "Plan and Execute Modes"],
  ["inspiration-library.md", "Inspiration Library"],
  ["material-scouting.md", "Material Scouting and Ranking"],
  ["image-to-code-fidelity.md", "Image-to-Code Fidelity Loop"],
  ["ui-designer-thinking.md", "UI Designer Thinking Model"],
  ["detail-critique.md", "Detail Critique"],
  ["acceptance.md", "UI Acceptance"],
];

export async function buildPrompt(root = ROOT) {
  const base = path.join(root, ".agents/skills/ui-design-agent");
  const source = await readFile(path.join(base, "SKILL.md"), "utf8");
  parseSkill(source);
  let body = source.replace(/^---\r?\n[\s\S]*?\r?\n---(?:\r?\n|$)/, "").trim();
  const parts = [];
  for (const [file, title] of references) {
    const anchor = title.toLowerCase().replaceAll(" ", "-");
    body = body.replaceAll(`(${"references/" + file})`, `(#${anchor})`);
    parts.push((await readFile(path.join(base, "references", file), "utf8")).trim());
  }
  return "<!-- Generated by npm run prompt:build. Edit .agents/skills/ui-design-agent, not this export. -->\n\n"
    + [body, ...parts].join("\n\n---\n\n") + "\n";
}

if (process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href) {
  try {
    const output = path.join(ROOT, "output/ui-design-agent.system.md");
    const prompt = await buildPrompt();
    await mkdir(path.dirname(output), { recursive: true });
    await writeFile(output, prompt);
    console.log(output);
  } catch (error) {
    console.error(error.message);
    process.exitCode = 1;
  }
}
