import { mkdir, readFile, writeFile, readdir } from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";
import { ROOT, parseSkill } from "./verify.mjs";

// Exported for tests/references-manifest.test.mjs: the manifest registry,
// the on-disk references/, and these export lists must stay four-way
// consistent (tooling/references-manifest.json is the registry of record).
export const references = [
  ["gate-protocol.md", "Gate Protocol"],
  ["motion-contract.md", "Web Motion Contract"],
  ["tool-routing.md", "Capability Routing"],
  ["spatial-media.md", "Spatial Media"],
  ["web3d-hud-architecture.md", "Web 3D HUD Architecture"],
  ["stitch-mcp.md", "Stitch MCP Call Logic"],
  ["design-contract.md", "Design Contract"],
  ["user-taste-profile.md", "User Taste Profile"],
  ["plan-execute.md", "Plan and Execute Modes"],
  ["inspiration-library.md", "Inspiration Library"],
  ["material-scouting.md", "Material Scouting and Ranking"],
  ["image-to-code-fidelity.md", "Image-to-Code Fidelity Loop"],
  ["ui-designer-thinking.md", "UI Designer Thinking Model"],
  ["detail-critique.md", "Detail Critique"],
  ["detail-constants.md", "Detail Constants"],
  ["typography-standards.md", "Typography Standards"],
  ["copy-contract.md", "Copy Contract"],
  ["dark-surface-standards.md", "Dark Surface Standards"],
  ["data-dense-surfaces.md", "Data-Dense Surfaces"],
  ["prototype-handover.md", "Prototype Handover Protocol"],
  ["video-craft.md", "Video Craft"],
  ["workflow-visualization.md", "Workflow Visualization"],
  ["product-readme.md", "Product README Standard"],
  ["acceptance.md", "UI Acceptance"],
];

// Lean export: the minimum set a hosting agent needs to run the chain with
// the user's taste and the quality gates. Everything else is route-on-demand.
export const leanReferences = new Set([
  "gate-protocol.md",
  "design-contract.md",
  "motion-contract.md",
  "acceptance.md",
  "user-taste-profile.md",
]);

// D1-04 可迁移性（纯函数，导出供 tests/kit.test.mjs 复算）：单文件导出必须
// 自包含——互引链接要么改写为文内锚点，要么退化为纯文本；不允许残留外部
// 宿主解析不了的相对文件链接（references/ 互引有 `references/x.md` 与裸
// `x.md` 两种写法；注册在案但 export:false 的文件（如 source-catalog.md）
// 永远不在导出内，其链接一律降级为纯文本）。
export function inlineReferenceLinks(text, { lean = false, unexported = [] } = {}) {
  let out = text;
  for (const [file, title] of references) {
    const anchor = title.toLowerCase().replaceAll(" ", "-");
    const esc = file.replaceAll(".", "\\.");
    const embedded = !lean || leanReferences.has(file);
    if (embedded) {
      out = out.replaceAll(`(${"references/" + file})`, `(#${anchor})`);
      out = out.replace(new RegExp(`\\]\\(${esc}\\)`, "g"), `](#${anchor})`);
    } else {
      out = out.replace(new RegExp(`\\[([^\\]]+)\\]\\(references/${esc}\\)`, "g"), "$1");
      out = out.replace(new RegExp(`\\[([^\\]]+)\\]\\(${esc}\\)`, "g"), "$1");
    }
  }
  for (const file of unexported) {
    const esc = file.replaceAll(".", "\\.");
    out = out.replace(new RegExp(`\\[([^\\]]+)\\]\\(references/${esc}\\)`, "g"), "$1");
    out = out.replace(new RegExp(`\\[([^\\]]+)\\]\\(${esc}\\)`, "g"), "$1");
  }
  return out;
}

export async function buildPrompt(root = ROOT, { lean = false } = {}) {
  const base = path.join(root, ".agents/skills/ui-design-agent");
  const source = await readFile(path.join(base, "SKILL.md"), "utf8");
  parseSkill(source);
  const onDisk = (await readdir(path.join(base, "references"))).filter((name) => name.endsWith(".md"));
  const exported = new Set(references.map(([file]) => file));
  const unexported = onDisk.filter((file) => !exported.has(file));
  const normalize = (text) => inlineReferenceLinks(text, { lean, unexported });
  const body = normalize(source.replace(/^---\r?\n[\s\S]*?\r?\n---(?:\r?\n|$)/, "").trim());
  const included = lean ? references.filter(([file]) => leanReferences.has(file)) : references;
  const parts = [];
  for (const [file] of included) {
    parts.push(normalize((await readFile(path.join(base, "references", file), "utf8")).trim()));
  }
  const tier = lean ? "npm run prompt:build:lean (lean tier)" : "npm run prompt:build";
  return `<!-- Generated by ${tier}. Edit .agents/skills/ui-design-agent, not this export. -->\n\n`
    + [body, ...parts].join("\n\n---\n\n") + "\n";
}

if (process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href) {
  try {
    const lean = process.argv.includes("--lean");
    const output = path.join(ROOT, lean ? "output/ui-design-agent.lean.md" : "output/ui-design-agent.system.md");
    const prompt = await buildPrompt(ROOT, { lean });
    await mkdir(path.dirname(output), { recursive: true });
    await writeFile(output, prompt);
    console.log(output);
  } catch (error) {
    console.error(error.message);
    process.exitCode = 1;
  }
}
