import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";
import { ROOT, parseSkill } from "./verify.mjs";

const references = [
  ["motion-contract.md", "Web Motion Contract"],
  ["tool-routing.md", "Capability Routing"],
  ["spatial-media.md", "Spatial Media"],
  ["web3d-hud-architecture.md", "Web 3D HUD Architecture"],
  ["stitch-mcp.md", "Stitch MCP Call Logic"],
  ["design-contract.md", "Design Contract"],
  ["user-taste-profile.md", "User Taste Profile"],
  ["plan-execute.md", "Plan and Execute Modes"],
  ["inspiration-library.md", "Inspiration Library"],
  ["material-scouting.md", "Material Scouting and Ranking"],
  ["image-to-code-fidelity.md", "Image-to-Code Fidelity Loop"],
  ["ui-designer-thinking.md", "UI Designer Thinking Model"],
  ["detail-critique.md", "Detail Critique"],
  ["product-readme.md", "Product README Standard"],
  ["acceptance.md", "UI Acceptance"],
];

// Lean export: the minimum set a hosting agent needs to run the chain with
// the user's taste and the quality gates. Everything else is route-on-demand.
const leanReferences = new Set([
  "design-contract.md",
  "motion-contract.md",
  "acceptance.md",
  "user-taste-profile.md",
]);

export async function buildPrompt(root = ROOT, { lean = false } = {}) {
  const base = path.join(root, ".agents/skills/ui-design-agent");
  const source = await readFile(path.join(base, "SKILL.md"), "utf8");
  parseSkill(source);
  let body = source.replace(/^---\r?\n[\s\S]*?\r?\n---(?:\r?\n|$)/, "").trim();
  const included = lean ? references.filter(([file]) => leanReferences.has(file)) : references;
  for (const [file, title] of included) {
    const anchor = title.toLowerCase().replaceAll(" ", "-");
    body = body.replaceAll(`(${"references/" + file})`, `(#${anchor})`);
  }
  if (lean) {
    for (const [file] of references) {
      if (leanReferences.has(file)) continue;
      body = body.replace(new RegExp(`\\[([^\\]]+)\\]\\(references/${file.replaceAll(".", "\\.")}\\)`, "g"), "$1");
    }
  }
  const parts = [];
  for (const [file] of included) {
    parts.push((await readFile(path.join(base, "references", file), "utf8")).trim());
  }
  const tier = lean ? "npm run prompt:build:lean (lean tier)" : "npm run prompt:build";
  return `<!-- Generated by ${tier}. Edit .agents/skills/ui-design-agent, not this export. -->\n\n`
    + [body, ...parts].join("\n\n---\n\n") + "\n";
}

if (process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href) {
  try {
    const lean = process.argv.includes("--lean");
    const output = path.join(ROOT, lean ? "output/ui-design-agent.lean.md" : "output/ui-design-agent.system.md");
    const prompt = await buildPrompt(ROOT, { lean });
    await mkdir(path.dirname(output), { recursive: true });
    await writeFile(output, prompt);
    console.log(output);
  } catch (error) {
    console.error(error.message);
    process.exitCode = 1;
  }
}
